### ISSUE TITLE
Handle case of table extension in PostgreSQL (fetching last insert id)

### ISSUE THREAD

**Issue by alkavan** [auraphp/Aura.SqlQuery#19]
Found an issue with query objects in cases you have one tables extending another one.

Consider the following table structure:

```
CREATE TABLE basic."table_A"
(
  id serial NOT NULL,
  field1 character varying(255),
  CONSTRAINT table_a_pkey PRIMARY KEY (id)
)
WITH (OIDS=FALSE);
ALTER TABLE basic."table_A" OWNER TO app;
```

```
CREATE TABLE basic."table_B"
(
-- Inherited from table basic."table_A":  id integer NOT NULL DEFAULT nextval('basic."table_A_id_seq"'::regclass),
-- Inherited from table basic."table_A":  field1 character varying(255),
  field2 character varying(255)
)
INHERITS (basic."table_A")
WITH (OIDS=FALSE);
ALTER TABLE basic."table_B" OWNER TO app;
```

And the following method in: https://github.com/auraphp/Aura.SqlQuery/blob/develop-2/src/Pgsql/Insert.php#L33

```
public function getLastInsertIdName($col)
{
    return "{$this->into}_{$col}_seq";
}
```

It fails to fetch the last insert id when inserting into table_B. the only way it was possible to fetch the correct last insert id is this:

```
$this->db->lastInsertId('basic.table_A_id_seq');
```

Like you can see I'm required talking directly to the db instance instead of using the insert object. don't think it's very optimal. another option is extending the query object and this also means eventually the query builder, also not very optimal.

I expect this to be handled "automatically" just like in the normal case. or for the query object to provide a method to adjust the sequence name.

**Comment by pmjones** [comment]
Believe it or not, this is kind of a tough problem, given the constraints of the package.  Let me explain a little.

The `getLastInsertIdName()` method is there so that, after an insert, you can call `$pdo->lastInsertId($insert->getLastInsertIdName())`. In non-Postgres cases, the name is `null` because the database tracks the last insert ID for you.  But for Postgres, `lastInsertId()` needs the sequence name. Thus, the `getLastInsertIdName()` builds that sequence name for you.

But as you note, Postgres may not use the name of the insert table for the sequence. It will use the parent table name if the insert table name extends it. The problem here is that the SqlQuery package does not examine the table structure at the database, so it has no way knowing if the insert table extends another table, and therefore the last insert ID name should be built differently.

Some options for fixing it:
1. One option would be to have the SqlQuery system inspect the schema in some way to auto-discover if the insert table extends another table, and so build the insert ID name properly. That option is a non-starter for various reasons, not least of which is that it would introduce a dependency (maybe only on PDO, but even so, that's something I'd like to avoid).
2. Another option is (as you noted elsewhere) is to have something like `$insert->setParentTable('parent_table_name')` and use that parent table name when building the last insert ID name. That would work fine, but I get the feeling that having to add that for Every. Single. Insert. would be a big hassle. It also doesn't lend itself to unspoken plans I have for a possible DataMapper system.
3. We could get rid of the `getLastInsertIdName()` method entirely, and make users of Postgres manually enter the sequence name when using `$pdo->lastInsertId()`. That has the same drawbacks of option 2 above.
4. The last thing I can think of is to allow a map of `table names => insert ID names` in the Insert object.  The QueryFactory could store those, and inject them into the Insert object at creation time; the `getLastInsertIdName()` method could then use the mapped name, or its existing logic if no mapped name exists.

That's a 5-minute assessment. Do you have other ideas on how to address this?

**Comment by pmjones** [comment]
Further, if table `foo` extends table `bar`, which extends table `baz`, I think that means an insert into `foo` uses `baz_id_seq` for the last insert ID. So it won't be enough to specify just one parent table; it would have to figure out the table hierarchy (even if we enter it in) and use the right sequence name for the topmost parent.

**Comment by pmjones** [comment]
Further consideration makes me think we might need a separate object, _not_ the Insert object, to track the map of last insert ID names.

**Comment by pmjones** [comment]
@alkavan take a look at these changes https://github.com/auraphp/Aura.SqlQuery/commit/4936b1c7122120eb68e5a657d6dd1510d5c86257?w=1 and let me know if that seems like the right direction

**Comment by pmjones** [comment]
@alkavan Any further thoughts on this? Does the commit above appear to solve the problem for you in a way that is useful?

**Comment by pmjones** [comment]
Fixed in https://github.com/auraphp/Aura.SqlQuery/commit/4936b1c7122120eb68e5a657d6dd1510d5c86257?w=1 -- thanks!
