### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Morthy** [auraphp/Aura.SqlQuery#200]
Hello,

It looks like there have been a quite a few commits to the 3.x branch in the 6 years since the last tag (2.7.1). Would it be possible to make a new tag?

2.7.1 has code which throws deprecation warnings in PHP 8.1 but has already been fixed in the 3.x branch, so it would be nice to upgrade.

**Comment by harikt** [comment]
Technically we can do a release for 3.x .

But I was looking at https://github.com/auraphp/Aura.SqlQuery/pull/142 .

I am not using Aura.SqlQuery for any projects and my time is very limited, so I fear whether people will blame me for not maintaining it as they want.

**Comment by harikt** [comment]
I did created a 3.0.0-alpha.1 .

This is what I am planning for the future 

1. Merge https://github.com/auraphp/Aura.SqlQuery/pull/142 or abandon 
2. Fix / close all the open issues if we cannot find a way to handle it.
3. Release 3.0.0 stable
4. If anyone is planning to start a new project, I recommned they should consider using Atlas or some other libraries because of my limited time and energy.

**Comment by harikt** [comment]
I am closing the issue for now. Feel free to comment if you have different ideas or expectations.
