### ISSUE TITLE
InsertInterface purpose?

### ISSUE THREAD

**Issue by pavarnos** [auraphp/Aura.SqlQuery#92]
Hi

I'm not understanding InsertInterface (and some of the other interfaces): they appear to be to be incomplete?

I'd like my code to depend on the interfaces rather than the concrete classes of Aura.SqlQuery but the interfaces are often missing useful methods. eg Common\Insert implements addRow() and addRows() but these are not in InsertInterface... is there a good reason for that?

**Comment by pmjones** [comment]
The problem in this case is that "bulk inserts" were added after InsertInterface went stable. In order to maintain BC, we can't change a stable interface to add methods, because that would break anyone else's implementation of the interface -- they would have to add the new methods to previously-running code. We can only add those methods to the interface in a major version release.

**Comment by pavarnos** [comment]
see also #108. Would be good to add the new reset*() methods too...
